/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ATM_app;

import java.io.IOException;
import java.util.Optional;

import ATM_app.Controller.WelcomeController;
import javafx.application.Application;
import javafx.scene.control.ButtonType;
import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import org.json.simple.parser.ParseException;
import javafx.scene.control.Alert;
public class ATMApp extends Application {

    private ATM atm;

    @Override
    public void start(Stage primaryStage) throws IOException, ParseException {

        FXMLLoader loader = new FXMLLoader(getClass().getResource("/Welcome.fxml"));
        Parent root = loader.load();

        WelcomeController welcomeController = loader.getController();
        atm = new ATM("src/main/resources/AllCards.json", "src/main/resources/ATMInfo.json");
        welcomeController.setATM(atm);

        Scene scene = new Scene(root);
        primaryStage.setTitle("XYZ ATM Banking");
        primaryStage.setScene(scene);

        primaryStage.setOnCloseRequest(e -> {
            e.consume();
            try {
                closeApplication(primaryStage);
            } catch (IOException ioException) {
                ioException.printStackTrace();
            }
        });

        primaryStage.show();
    }

    private void closeApplication(Stage stage) throws IOException {
        Alert alert = new Alert(Alert.AlertType.CONFIRMATION);
        alert.setTitle("Close Window Alert");
        alert.setContentText("Do you want to close the application?");
        Optional<ButtonType> choice = alert.showAndWait();
        if (choice.get() == ButtonType.OK) {
            atm.saveATMInfo("src/main/resources/ATMInfo.json");
            atm.saveCardInfo("src/main/resources/AllCards.json");
            stage.close();
        }
        else {
            return;
        }
    }

    public static void main(String[] args) {
        launch(args);
    }
    
}
